// Package schema serves the JSON Schema for noodge.yaml.
//
// The schema is generated by tools/gen-schema and committed, rather than
// produced at runtime: generation reads the Go doc comments in internal/config
// to build the field descriptions, and a shipped binary has no source to read
// from. CI regenerates it and fails if the committed copy has drifted.
package schema

import _ "embed"

//go:embed noodge.schema.json
var jsonSchema []byte

// JSON returns the schema document.
func JSON() []byte { return jsonSchema }
